# 项目: OneTouch 一键连配置 版本v1.0
# 日期：2024年10月10日
# 地址: https://github.com/666OS
# 频道: https://t.me/Pinched666

# 锚点
PProviders: &PProviders {type: http, interval: 86400, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 300}, filter: '^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))'}
# 填写订阅,名称不能重复
proxy-providers:
  机场A: {<<: *PProviders, url: '机场订阅地址', override: {additional-prefix: '[A] '}}
  机场B: {<<: *PProviders, url: '机场订阅地址', override: {additional-prefix: '[B] '}}

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query

proxies:
  - {name: 直连, type: direct, udp: true}

proxy-groups:
  - {name: 一键连, type: select, include-all: true, icon: https://mirror.ghproxy.com/https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/image/mihomo-logo.png}

rule-providers: 
  private_ip: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/private_ip.mrs}
  cn_domain: {type: http, interval: 86400, behavior: domain, format: mrs, url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/cn.mrs}
  cn_ip:     {type: http, interval: 86400, behavior: domain, format: mrs, url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/cn_ip.mrs}
  
rules: 
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,cn_domain,直连
  - AND,((NOT,((RULE-SET,cn_ip,直连))),(OR,((IP-CIDR,0.0.0.0/0),(IP-CIDR6,::/0)))),一键连
  - MATCH,一键连
